[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "pydantic",
    "python-multipart",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "websockets",
    "openai-whisper",
    "pyttsx3",
    "soundfile",
    "numpy",
    "aiortc",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
]
